---
title: "Untitled"
author: "Aleksandra Dacko"
date: "11/15/2022"
output: html_document

---

```{r}
library(DT)
library(here)
library("readxl")
library(dplyr)
library(r2d3)
library(shiny)
library(shinythemes)
library(shinydashboard)
library(packcircles)
library(ggplot2)
library(RColorBrewer)
library(htmlwidgets)
library("digest")
library("bit")
library(shinySignals)
library(plotly)
library(networkD3)
library(tidyverse)
library(htmlwidgets)
library(devtools)
library(shinyWidgets)
```


```{r cars}
DS<- read_excel("Data/DS courses UU.xlsx")
short<- read_excel("Data/short.xlsx")
levels_names<-c("1","2","3","M","Post-academic")
cource_names<-unique(DS$Course_type)
faculty_names<-complete.cases(unique(DS$Faculty))
```


```{r }

shinyApp(
  ui = fluidPage(navbarPage("Data Science Related Courses at UU", theme = shinytheme("paper"),
                  tabPanel("Topics overview",
                           sidebarLayout(
                             column(width = 4,
                             h6("The dashboard is an interactive tool for exploring Utrecht University's data science courses."),
                             wellPanel(
                               shinyjs::useShinyjs(),
                               h4("Filters:"), 
                               selectInput("level", "Education Level:",choices = 
                                          c("Introduction Bachelor" = "1",
                                             "Intermediate Bachelor" =  "2" ,
                                            "Advance Bachelor" = "3",
                                              "Master"="M",
                                              "Post-academic"="Post-academic",
                                            "All"="all"),selected ='all'),
                               selectInput("faculty", "The Faculty:",
                                          c("Faculty of Social Sciences" = "Faculty of Social Sciences",
                                             "Faculty of Science" = "Faculty of Science")
                                          ),
                                selectInput("course", "Course type:",
                                              list(`Regular` = c("Course","Practical","Research project"),
                                                    `Summer School` = c("summer","winter","online"))
                                            ),
                               actionButton(inputId = "Reset_table", label = "Reset table"),
                               tags$script("
                                    Shiny.addCustomMessageHandler('resetValue', function(variableName) {
                                      Shiny.onInputChange(variableName, null);
                                    });
                                  ")
                               )
                               
                             ),
                             column(width = 8,
                                    
                               h4("Main topics covered",align = "center"),
                                d3Output("d3"),
                               h5(textOutput("text")),
                                DT::dataTableOutput('table')
                               
                             )
                           )
                             
                           ),
                  tabPanel("Topics overview plotly",
                             mainPanel(
                               h2("Main topics covered"),
                               forceNetworkOutput(outputId = "net")
                           )
                             
                           )
                 
  )),
server = function(input, output, session) { 
  
  level=reactive(input$level)
  course=reactive(input$course)
  faculty=reactive(input$faculty)

  observeEvent(input$Reset_table, {
    shinyjs::reset()
    session$sendCustomMessage(type = "resetValue", message = "click_event")
  })
      

  output$d3 <- renderD3({
    if(level()=="all"){
      data <- DS %>% select(c(1,4,6,19:60)) %>% filter(Faculty==faculty(),DS$Course_type==course()) %>% pivot_longer(where(is.numeric)) %>% group_by(name) %>% summarise(value=sum(value,na.rm =T)) %>% filter(value>0)
    }else{
      data <- DS %>% select(c(1,4,6,19:60)) %>% filter(Faculty==faculty(),Level==level(),DS$Course_type==course()) %>% pivot_longer(where(is.numeric)) %>% group_by(name) %>% summarise(value=sum(value,na.rm =T)) %>% filter(value>0)
   }
       
    colnames(data)<-c("id","value")
    data<-left_join(data,short, by="id")
    
    
      if (nrow(data) == 0){return(paste0("No courses correcsponding to chosen matrix"))}else{
        r2d3(data=data, d3_version = 4, script ="bubble.js")
        }
  })
  
  output$text<-renderText({
    if(is.null(input$click_event)){
      paste0("The database of courses")
    }else{
       paste0("The database of courses that cover the ", input$click_event," topics")
    }
         })
  
output$table <- DT::renderDataTable({
  
  if(is.null(input$click_event)){
    if(level()=='all'){
    DS %>% filter(Faculty==faculty(),DS$Course_type==course()
                  ) %>% select(c(1,3,5,7,8,9,12))
  }else{
    DS %>% filter(Faculty==faculty(),Level==level(),DS$Course_type==course()
                  ) %>% select(c(1,3,5,7,8,9,12))
  }}else{
    if(level()=='all'){
    DS %>% filter(Faculty==faculty(),DS$Course_type==course(),(!!sym(input$click_event))==1
                  ) %>% select(c(1,3,5,7,8,9,12))
  }else{
    DS %>% filter(Faculty==faculty(),Level==level(),DS$Course_type==course(),(!!sym(input$click_event))==1
                  ) %>% select(c(1,3,5,7,8,9,12))
  }
    
  }
  
      },server = F,options = list(searching = FALSE))
  
    
output$net <- renderForceNetwork({
      nodes <- read.csv("https://kateto.net/workshops/data/Dataset1-Media-Example-NODES.csv", header=T, as.is=T)
    links <- read.csv("https://kateto.net/workshops/data/Dataset1-Media-Example-EDGES.csv", header=T, as.is=T)
    links.d3 <- data.frame(from=as.numeric(factor(links$from))-1, 
                 to=as.numeric(factor(links$to))-1 )
    nodes.d3 <- cbind(idn=factor(nodes$media, levels=nodes$media), nodes)
    forceNetwork(Links = links.d3, Nodes = nodes.d3, Source="from", Target="to",
               NodeID = "idn", Group = "type.label",linkWidth = 1,
               linkColour = "#afafaf", fontSize=12, zoom=T, legend=T,
               Nodesize=6, opacity = 1, charge=-600, 
               width = 600, height = 600)})
                 
}
)
```
```{r}
data <- DS %>% select(c(1,4,6,19:60)) %>% filter(Faculty=="Faculty of Science", Level=="M") %>% pivot_longer(where(is.numeric)) %>% group_by(name) %>% summarise(value=sum(value,na.rm =T)) %>% filter(value>0) 
    colnames(data)<-c("id","value")
data<-left_join(data,short, by="id")
```

