---
title: "Untitled"
author: "Aleksandra Dacko"
date: "11/15/2022"
output: html_document

---

```{r,warning=False}
library(DT)
library(here)
library("readxl")
library(dplyr)
library(r2d3)
library(shiny)
library(shinythemes)
library(shinydashboard)
library(packcircles)
library(ggplot2)
library(RColorBrewer)
library(htmlwidgets)
library("digest")
library("bit")
library(shinySignals)
library(plotly)
library(networkD3)
library(tidyverse)
library(htmlwidgets)
library(devtools)
library(shinyWidgets)
```


```{r cars}
DS<- read_excel("Data/DS courses UU.xlsx")
short<- read_excel("Data/short.xlsx")
levels_names<-c("1","2","3","M","Post-academic")
levels_names_discr<-c("Introduction Bachelor","Intermediate Bachelor","Advance Bachelor","Master","Post-academic")
course_names<-c("Course","Practical","Research project","summer","winter","online")
course_names_discr<-c("Course","Practical","Research project","Summer courses","Winter courses","Online")
faculty_names<-c(unique(DS$Faculty)[complete.cases(unique(DS$Faculty))])
```


```{r }

shinyApp(
  ui = fluidPage(navbarPage("Data Science Related Courses at UU", theme = shinytheme("paper"),
                  tabPanel("Topics overview",
                           sidebarLayout(
                             column(width = 4,
                             h6("The dashboard is an interactive tool for exploring Utrecht University's data science courses."),
                             wellPanel(
                               shinyjs::useShinyjs(),
                               h4("Filters:"), 
                               selectInput("level", "Education Level:",choices = 
                                          c("Introduction Bachelor" = "1",
                                             "Intermediate Bachelor" =  "2" ,
                                            "Advance Bachelor" = "3",
                                              "Master"="M",
                                              "Post-academic"="Post-academic",
                                            "All"="all"),selected ='all'),
                               selectInput("faculty", "The Faculty:",
                                          c("Faculty of Social Sciences" = "Faculty of Social Sciences",
                                             "Faculty of Science" = "Faculty of Science",
                                            "Faculty of Medicine"="Faculty of Medicine",
                                            "Faculty of Veterinary"= "Faculty of Veterinary Medicine",
                                            "Faculty of Geoscience" = "Faculty of Geoscience")
                                          ),
                                selectInput("course", "Course type:",
                                              list(`Regular` = c("Course","Practical","Research project"),
                                                    `Summer School` = c("summer","winter","online"))
                                            ),
                               actionButton(inputId = "Reset_table", label = "Reset table"),
                               tags$script("
                                    Shiny.addCustomMessageHandler('resetValue', function(variableName) {
                                      Shiny.onInputChange(variableName, null);
                                    });
                                  ")
                               )
                               
                             ),
                             column(width = 8,
                                  
                               h4("Main topics covered",align = "center"),
                                d3Output("d3"),
                               h5(textOutput("text")),
                                DT::dataTableOutput('table')
                               
                             )
                           )
                             
                           ),
                  tabPanel("Overview",
                           column(width = 12,
                           wellPanel(
                             selectInput("overview", "Overview:",choices = 
                                          c("Faculty" = "Faculty",
                                            "Level"="Level",
                                            "Course type"="Course_type")),
                             numericInput("min_courses","Minimum number of courses: ",min = 1,max=120,value = 1),
                             actionButton("action1", "Update the view")
     
                           )),
                            column(width = 12,
                           uiOutput("plots")
                             )
                             
                           )
                 
  )),
server = function(input, output, session) { 
  
  level=reactive(input$level)
  course=reactive(input$course)
  faculty=reactive(input$faculty)

  observeEvent(input$Reset_table, {
    session$sendCustomMessage(type = "resetValue", message = "click_event")
  })
      

  output$d3 <- renderD3({
    if(level()=="all"){
        data <- DS %>% select(c(1,2,4,6,19:60)) %>% filter(Faculty==faculty(),Course_type==course()) %>%
                pivot_longer(where(is.numeric)) %>% group_by(name) %>% 
                summarise(value=sum(value,na.rm =T)) %>% filter(value>0)
       colnames(data)<-c("id","value")
       data<-left_join(data,short, by="id")
       r2d3(data=data, d3_version = 4, script ="bubble.js")
      }else{
        data <- DS %>% select(c(1,2,4,6,19:60)) %>% filter(Faculty==faculty(),Level==level())
        if(course() %in% data$Course_type){
          data<-data %>% filter(Course_type==course()) %>% pivot_longer(where(is.numeric)) %>%
            group_by(name) %>% summarise(value=sum(value,na.rm =T)) %>% filter(value>0)
          colnames(data)<-c("id","value")
          data<-left_join(data,short, by="id")
          r2d3(data=data, d3_version = 4, script ="bubble.js")
          }else{
            data<-data.frame(id="No data",value=20,short="No data avaiable")
            r2d3(data=data, d3_version = 4, script ="bubble.js")
          }
        }
    })
  
  output$text<-renderText({
    if(is.null(input$click_event)){
      paste0("The database of courses")
    }else{
       paste0("The database of courses that cover the ", input$click_event," topics")
    }
         })

  
    
  input_plots <- reactiveValues()
  observeEvent(input$action1,{
    input_plots$over<-input$overview
    input_plots$min_course<-input$min_courses
     if(input_plots$over=='Faculty'){
        names_for_bubble<-get("faculty_names")
        plot_titles<-get("faculty_names")
      }else if(input_plots$over=='Level'){
        names_for_bubble<-get("levels_names")
        plot_titles<-get("levels_names_discr")
        }else if(input_plots$over=='Course_type'){
          names_for_bubble<-get("course_names")
          plot_titles<-get("course_names_discr")}
    for (i in 1:length(names_for_bubble)) {
      local({
      my_i <- i
      plotname <- paste("plot", my_i, sep="")
      data <- DS %>% select(c(1,2,4,6,19:60))
      names<-names_for_bubble[i]
      output[[plotname]] <- renderD3({
        data<- data  %>% filter(!!sym(input_plots$over)==names) %>% pivot_longer(where(is.numeric)) %>% group_by(name) %>%
        summarise(value=sum(value,na.rm =T)) 
        if(all(data$value<input_plots$min_course)){
          data<-data.frame(id="No data",value=20,short="No data avaiable")
        }else{
          data<-data %>% filter(value>(input_plots$min_course-1))
          colnames(data)<-c("id","value")
          data<-left_join(data,short, by="id")
          }
        r2d3(data=data, d3_version = 4, script ="bubble_2.js")})
    })
    }
    output$plots <- renderUI({
      
     
    plot_output_list <- lapply(1:length(names_for_bubble), function(i) {
     plotname <- paste("plot", i, sep="")
      column(width = 6,
              h4(plot_titles[i],align = "center"),
               tags$div(style = "margin-top: 10px; margin-bottom: 10px;", d3Output(plotname))
             )
    } )

    do.call(tagList, plot_output_list)
  })})
    
output$table <- DT::renderDataTable({
  
  if(is.null(input$click_event)){
    if(level()=='all'){
      DS %>% filter(Faculty==faculty(),DS$Course_type==course()) %>% select(c(1,3,5,7,8,9,12))
      }else{
        DS %>% filter(Faculty==faculty(),Level==level(),DS$Course_type==course())%>%select(c(1,3,5,7,8,9,12))
        }}else{
          if(level()=='all'){
            DS %>% filter(Faculty==faculty(),DS$Course_type==course(),(!!sym(input$click_event))==1)%>% select(c(1,3,5,7,8,9,12))
            }else{
              DS %>% filter(Faculty==faculty(),Level==level(),DS$Course_type==course(),(!!sym(input$clik_event))==1)%>% select(c(1,3,5,7,8,9,12))
            }
          }
},server = F,options = list(searching = FALSE))



})
```

```{r}
data <- DS %>% select(c(1,2,4,6,19:60)) %>% filter( Course_type=="Research project") %>% pivot_longer(where(is.numeric)) %>% group_by(name) %>% summarise(value=sum(value,na.rm =T)) %>% filter(value>0) 
if("1" %in% data$Level){
  data<-filter(Level=="1")
}else{
  data<-NULL
}
    colnames(data)<-c("id","value")
data<-left_join(data,short, by="id")
data
```

```{r}
library(shiny)
runApp(shinyApp(
    ui = fluidPage(
        shinyjs::useShinyjs(),
        numericInput("val", "Choose value (max 10)", 5),
        sliderInput(inputId = "range",
                    label = "Range",
                    min = 0,
                    max = 10,
                    step = 0.1,
                    value = c(0,2))
    ),
    server = function(input, output, session) {
        observeEvent(input$val, {
            if(input$val <= 10){
                shinyjs::enable("range")
            }else{
                shinyjs::disable("range")
            }
        })
    }
))

```


